lib/eligit_web/router.ex
defmodule EligitWeb.Router do
  use EligitWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EligitWeb do
    pipe_through :browser

    get "/", PageController, :index
    post "/", PageController, :create, as: :report
    post "/async", PageController, :async_create, as: :async_report
  end

  # Other scopes may use custom stacks.
  # scope "/api", EligitWeb do
  #   pipe_through :api
  # end
end

lib/eligit/application.ex
defmodule Eligit.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Eligit.Repo,
      # Start the endpoint when the application starts
      EligitWeb.Endpoint
      # Starts a worker by calling: Eligit.Worker.start_link(arg)
      # {Eligit.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Eligit.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    EligitWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/eligit/repo.ex
defmodule Eligit.Repo do
  use Ecto.Repo,
    otp_app: :eligit,
    adapter: Ecto.Adapters.Postgres
end

lib/gitstat/cake.ex
defmodule Gitstat.Cake do
  use GenServer

  # Client Interface

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, :ok, opts)
  end

  def async_run(pid, receiver, path) do
    GenServer.cast(pid, { :run, receiver, path })
  end

  # Server Interface

  def init(:ok) do
    state = []
    { :ok, state }
  end

  def handle_cast({ :run, receiver, path }, state) do
    paths_to_analyze = analyse(path)
    result = process_results(receiver, %{}, paths_to_analyze)
    send receiver, { :total, result }
    { :noreply, state }
  end

  defp analyse(path) do
    paths = Path.wildcard("#{path}/**/*.*")
    paths
    |> Enum.each( fn(path) ->
      {:ok, libra } = Gitstat.Cake.Libra.start_link()
      Gitstat.Cake.Libra.async_run(libra, self(), path)
    end)
    Enum.count(paths)
  end

  defp process_results(receiver, result, 0) do
    result
  end

  defp process_results(receiver, result, expected_messages) do
    receive do
      { :ok,  %{ language: nil } = payload } ->
        process_results(receiver, result, expected_messages - 1)
      { :ok,  %{ size: size, language: language } = payload } ->
        result = Map.update(result, language, size, &(&1 + size))
        Process.sleep(100) # This is used only to slow down and see the pie cart :)
        send receiver, { :partial, result }
        process_results(receiver, result, expected_messages - 1)
      { :error, payload } ->
        process_results(receiver, result, expected_messages - 1)
    end
  end
end

lib/gitstat/cake/libra.ex
defmodule Gitstat.Cake.Libra do
  use GenServer

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, :ok, opts)
  end

  def async_run(pid, receiver, path) do
    GenServer.cast(pid, { :run, receiver, path })
  end

  def init(:ok) do
    state = []
    { :ok, state }
  end

  def handle_cast({:run, receiver, path}, state) do
    { status, payload } = stat(path)
    send receiver, { status, payload }
    { :noreply, state }
  end

  defp stat(path) do
    %{size: size, type: type} = path |> File.stat!
    ext = Path.extname(path)
    { :ok, %{size: size, type: type, ext: ext, language: Gitstat.file_type(ext)} }
  end
end

lib/gitstat/fame.ex
defmodule Gitstat.Fame do
  use GenServer

  # Client Interface

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, :ok, opts)
  end

  def run(pid, path) do
    GenServer.call(pid, { :run, path })
  end

  def async_run(pid, receiver, path) do
    GenServer.cast(pid, { :run, receiver, path })
  end

  # Server Interface

  def init(:ok) do
    state = []
    { :ok, state }
  end

  def handle_call({:run, path}, _from, state) do
    result = run(path)
    { :reply, result, state }
  end

  def handle_cast({:run, receiver, path}, state) do
    result = run(path)
    send receiver, { :fame, result }
    { :noreply, state }
  end

  defp run(path) do
    {output, 0} = System.cmd("git", ["shortlog", "--summary", "--numbered", "--all"], cd: path)

    output
    |> String.split("\n")
    |> Enum.map(fn(x) -> Regex.run(~r/\A\s+(\d+)\s+(.+)\z/u, x, capture: :all_but_first) end)
  end
end

lib/gitstat/gitstat.ex
defmodule Gitstat do
  @file_types %{
    ".rb" => "ruby",
    ".rake" => "ruby",
    ".ru" => "ruby",
    ".rdoc" => "ruby",
    ".gemspect" => "ruby",
    ".js" => "javascript",
    ".javascript" => "javascript",
    ".jsx" => "javascript",
    ".coffee" => "javascript",
    ".css" => "css",
    ".styles" => "css",
    ".html" => "html",
    ".slim" => "html",
    ".haml" => "html",
    ".eex" => "html",
    ".ex" => "elixir",
    ".exs" => "elixir"
  }

  def file_type(extension) do
    Map.get(@file_types, extension)
  end
end

lib/eligit_web/controllers/page_controller.ex
require IEx
require Gitstat

defmodule EligitWeb.PageController do
  use EligitWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  # def create(conn, %{ "repo" => %{ "url" => url }} = params) do
  #   # First win!!! TODO: refactor all this shit! =D
  #   random_string = :crypto.strong_rand_bytes(12) |> Base.url_encode64 |> binary_part(0, 12)
  #   repo_local_path = "/tmp/#{random_string}"
  #   File.rm_rf!(repo_local_path)
  #   File.mkdir!(repo_local_path)
  #   { clone_status, repo } = Git.clone [url, repo_local_path]

  #   { :ok, pid } = Gitstat.Fame.start_link()
  #   fame = Gitstat.Fame.run(pid, repo_local_path) |> Enum.reject &is_nil/1
  #   File.rm_rf!(repo_local_path)
  #   render(conn, "report.html",
  #     url: url,
  #     clone_status: clone_status,
  #     repo: repo,
  #     fame: fame
  #   )
  # end

  def async_create(conn, %{ "repo" => %{ "url" => url }}) do
    random_string = :crypto.strong_rand_bytes(12) |> Base.url_encode64 |> binary_part(0, 12)
    repo_local_path = "/tmp/#{random_string}"
    File.rm_rf!(repo_local_path)
    File.mkdir!(repo_local_path)
    Git.clone [url, "--depth=1", repo_local_path]


    { :ok, pid } = Gitstat.Cake.start_link()
    Gitstat.Cake.async_run(pid, self(), repo_local_path)

    broadcast_cakes()

    File.rm_rf!(repo_local_path)

    text conn, "console.log('OMG')"
  end

  defp broadcast_cakes do
    receive do
      {:partial, payload} ->
         EligitWeb.Endpoint.broadcast!("room:lobby", "cake", %{ result: payload })
         broadcast_cakes()
      {:total, payload} ->
         EligitWeb.Endpoint.broadcast!("room:lobby", "cake", %{ result: payload })
    end
  end
end

lib/eligit_web/views/error_view.ex
defmodule EligitWeb.ErrorView do
  use EligitWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/eligit_web/views/layout_view.ex
defmodule EligitWeb.LayoutView do
  use EligitWeb, :view
end

lib/eligit_web/views/page_view.ex
defmodule EligitWeb.PageView do
  use EligitWeb, :view
end

lib/eligit_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Eligit</title>

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" 
      integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
      crossorigin="anonymous">
    <link rel="stylesheet" 
      href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" 
      integrity="sha256-7O1DfUu4pybYI7uAATw34eDrgQaWGOfMV/8erfDQz/Q="
      crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="<%= Routes.static_path(@conn, "/css/app.css") %>" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Eligit</a>
      </div>
    </nav>

    <%= render @view_module, @view_template, assigns %>

    <!-- Footer -->
    <footer class="footer bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
            <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
            <p class="text-muted small mb-4 mb-lg-0">&copy; Eligit. Created with ☕ and ❤ in Italy during SpawnFest 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <script 
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" 
      integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl"
      crossorigin="anonymous"></script>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.3.0/chartkick.min.js"
      integrity="sha256-pKi+C/L3JqiD10GzkevwyZ+pUZuKi5BxbPZiCg/Val4="
      crossorigin="anonymous"></script>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>

</html>

lib/eligit_web/templates/page/index.html.eex
    <!-- Masthead -->
    <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Stats for repo</h1>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <%# <%= form_tag Routes.report_path(@conn, :create) do %1> %>
            <%#   <div class="form-row"> %>
            <%#     <div class="col-12 col-md-9 mb-2 mb-md-0"> %>
            <%#       <%= text_input :repo, :url, class: "form-control form-control-lg", placeholder: "http://" %1> %>
            <%#     </div> %>
            <%#     <div class="col-12 col-md-3"> %>
            <%#       <%= submit "Give me stats!", class: "btn btn-block btn-lg btn-primary" %1> %>
            <%#     </div> %>
            <%#   </div> %>
            <%# <% end %1> %>

            <%= form_tag Routes.async_report_path(@conn, :async_create), class: 'remote' do %>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <%= text_input :repo, :url, class: "form-control form-control-lg", placeholder: "https://", value: "https://github.com/phoenixframework/phoenix.git" %>
                </div>
                <div class="col-12 col-md-3">
                  <%= submit "Give me stats!", class: "btn btn-block btn-lg btn-primary", id: 'cake-submit' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-xl-12 mx-auto mt-5">
            <div id='cake-output' style='height: 500px'></div>
          </div>
        </div>
      </div>
    </header>

lib/eligit_web/templates/page/report.html.eex
    <!-- Masthead -->
    <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Stats for repo</h1>
            <%= @url %>
            <%= @clone_status %>
            <%= @repo.path %>
          </div>
        </div>
        <div class="row">
          <table class="table table-striped table-dark">
            <thead>
              <tr>
                <th scope="col">Ranking</th>
                <th scope="col">Commits count</th>
                <th scope="col">Name</th>
              </tr>
            </thead>
            <tbody>
              <%= for {committer, i} <- Enum.with_index(@fame) do %>
                <tr>
                  <td><%= i+1 %></td>
                  <td><%= Enum.at(committer,0) %></td>
                  <td><%= Enum.at(committer,1) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

        </div>
      </div>
    </header>